version: 2

# TODO: ENHANCEME: (tatsuya6502) Utilize Circle CI cache for the following items:
# - The "update" tool (written in Rust) with Cargo's crates.io-index
# - node_modules

jobs:
  build:
    docker:
      - image: hrektts/mdbook:0.2.1
    parallelism: 1
    steps:
      - checkout
      # Remove .gitconfig added by Circle CI as cargo doesn't support ssh authorization
      - run: rm -f ~/.gitconfig
      - run: mdbook build
      - run: mdbook test
      - store_artifacts:
          path: book
      - deploy:
          name: If master branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master.sh
            fi
